title: Bambooom
author: bambooom
description: personal blog
disqus_shortname: bamboooom
highlighter: null
permalink: /:title

url:
baseurl:

sass:
  sass_dir: public/css
  style: :compressed

links:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: GitHub
    url: http://github.com/bambooom
    external: true
  - title: instagram
    url: https://www.instagram.com/milkymono
    external: true
  - title: feed
    url: /feed.xml