title:            Bambooom
description:      All those moments will be lost in time. Like rain in tears.
url:              http://bambooom.github.io
signoff:          bambooom # Your name.
encoding:         UTF-8
disqus_shortname: bamboooom # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          http://bambooom.github.io
    external:     true
  - name:         GitHub
    url:          http://github.com/bambooom
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
